### ISSUE TITLE
Strider crashes on new jobs started from a Pull Request that has been rebased

### ISSUE THREAD

**Issue by bitwit** [Strider-CD/strider-github-status#5]
Some more info here https://github.com/Strider-CD/strider/issues/745

Confirmed in 1.6.x of Core strider

**Comment by phiros** [comment]
@jaredly or @knownasilya are there any plans to fix this?
This feature is very important for larger projects on github...

BTW: It would maybe make sense to integrate this plugin into the github plugin.

**Comment by knownasilya** [comment]
@phiros I can look into this before the next release. Thanks for bringing this up again.

**Comment by bitwit** [comment]
Closing this issue as it appears it was a core strider issue. See https://github.com/Strider-CD/strider/pull/832
